name: literature_harmonization
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.11.*
  - pip
  - pandas
  - numpy
  - openpyxl
  - ruamel.yaml
  - click
  - cloup
  - pysam
  - pip:
      - git+https://github.com/ht-diva/gwaspipe.git@main
